name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Wine
        run: |
          if [ ! -d ~/.wine ]; then
            sudo dpkg --add-architecture i386 
            wget -nc https://dl.winehq.org/wine-builds/winehq.key
            sudo apt-key add winehq.key
            sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 
            sudo apt update
            sudo apt install --install-recommends winehq-stable
          fi

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Dependencies
        run: yarn run build

      - name: Package
        run: yarn run package

      - name: Get version
        id: package
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Get latest tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Check if tag exists
        id: check
        run: |
          if [ "${{ steps.previoustag.outputs.tag }}" = "v${{ env.version }}" ]; then
            echo "exists=0" >> $GITHUB_ENV
          else
            echo "exists=1" >> $GITHUB_ENV
          fi

      - name: Create Release
        id: create_release
        if: steps.check.outputs.exists != '1'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: true
          prerelease: false

      - name: Create zip of directory
        if: steps.check.outputs.exists != '1'
        run: |
          zip -r worksmart-notifier-win32-x64.zip worksmart-notifier-win32-x64

      - name: Upload Release Asset
        if: steps.check.outputs.exists != '1'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./worksmart-notifier-win32-x64.zip
          asset_name: worksmart-notifier-win32-x64.zip
          asset_content_type: application/zip
