name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Wine
        uses: actions/cache@v3
        with:
          path: ~/.wine
          key: ${{ runner.os }}-wine
          restore-keys: |
            ${{ runner.os }}-wine

      - name: Install Wine
        run: |
          if [ ! -d "~/.wine" ]; then
            sudo dpkg --add-architecture i386 
            wget -nc https://dl.winehq.org/wine-builds/winehq.key
            sudo apt-key add winehq.key
            sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 
            sudo apt update
            sudo apt install --install-recommends winehq-stable
          fi

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Dependencies
        run: yarn run build

      - name: Package
        run: yarn run package

      - name: Get version
        id: package
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check
        run: |
          TAG_EXISTS=$(curl --silent https://api.github.com/repos/$GITHUB_REPOSITORY/git/ref/tags/v${{ env.version }} > /dev/null; echo $?)
          echo "exists=$TAG_EXISTS" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        if: steps.check.outputs.exists != '1'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Create zip of directory
        if: steps.check.outputs.exists != '1'
        run: |
          zip -r worksmart-notifier-win32-x64.zip worksmart-notifier-win32-x64

      - name: Upload Release Asset
        if: steps.check.outputs.exists != '1'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./worksmart-notifier-win32-x64.zip
          asset_name: worksmart-notifier-win32-x64.zip
          asset_content_type: application/zip
